// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcdataservice.proto

package top.lilixin.grpc.api;

public interface RPCDateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.lilixin.grpc.api.RPCDateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string serverDate = 1;</code>
   */
  java.lang.String getServerDate();
  /**
   * <code>optional string serverDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerDateBytes();
}
