// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcdataservice.proto

package top.lilixin.grpc.api;

public interface RPCDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:top.lilixin.grpc.api.RPCDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>optional string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
